### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by pavelxx1** [wisnunugroho21/reinforcement_learning_ppo_rnd#10]
Hi, thx for repo!
I have an error while run test episodes

```
Traceback (most recent call last):
  File "ppo_frozenlake_notslippery_tensorflow.py", line 640, in <module>
    main()
  File "ppo_frozenlake_notslippery_tensorflow.py", line 588, in main
    agent.update_ppo()          
  File "ppo_frozenlake_notslippery_tensorflow.py", line 407, in update_ppo
    for states, actions, rewards, dones, next_states in self.memory.get_all_tensor().batch(batch_size):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1642, in batch
    return BatchDataset(self, batch_size, drop_remainder)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4115, in __init__
    **self._flat_structure)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 596, in batch_dataset_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Batch size must be greater than zero. [Op:BatchDatasetV2]
```

**Comment by wisnunugroho21** [comment]
Thanks for the report. 
I will fix the bug
